# Generated by Django 4.2.15 on 2026-06-09 13:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bottles', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_appreciation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('appreciation_rate', models.FloatField(default=0)),
                ('by_category', models.JSONField(default=dict)),
                ('by_country', models.JSONField(default=dict)),
                ('by_vintage', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '收藏统计',
                'verbose_name_plural': '收藏统计',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='酒品名称')),
                ('chateau', models.CharField(max_length=200, verbose_name='酒庄')),
                ('region', models.CharField(max_length=100, verbose_name='产区')),
                ('country', models.CharField(max_length=50, verbose_name='国家')),
                ('vintage', models.IntegerField(verbose_name='年份')),
                ('category', models.CharField(choices=[('red', '红葡萄酒'), ('white', '白葡萄酒'), ('rose', '桃红葡萄酒'), ('sparkling', '起泡酒'), ('dessert', '甜酒'), ('fortified', '加强酒')], max_length=20, verbose_name='类型')),
                ('grape_variety', models.CharField(max_length=200, verbose_name='葡萄品种')),
                ('alcohol_content', models.FloatField(verbose_name='酒精度(%)')),
                ('bottle_size', models.FloatField(default=0.75, verbose_name='容量(L)')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量(瓶)')),
                ('purchase_date', models.DateField(verbose_name='购买日期')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='购买价格(元)')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='当前估值(元)')),
                ('last_valuation_date', models.DateField(auto_now=True, verbose_name='最近估值日期')),
                ('cellar_location', models.CharField(max_length=50, verbose_name='酒窖位置')),
                ('status', models.CharField(choices=[('cellared', '窖藏中'), ('drinking', '适饮期'), ('peak', '巅峰期'), ('declining', '衰退期'), ('sold', '已售出'), ('mortgaged', '已抵押')], default='cellared', max_length=20, verbose_name='状态')),
                ('drinking_window_start', models.IntegerField(verbose_name='适饮期开始年份')),
                ('drinking_window_end', models.IntegerField(verbose_name='适饮期结束年份')),
                ('tasting_notes', models.TextField(blank=True, verbose_name='品鉴笔记')),
                ('storage_notes', models.TextField(blank=True, verbose_name='存储笔记')),
                ('image_url', models.URLField(blank=True, verbose_name='图片链接')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '酒品',
                'verbose_name_plural': '酒品',
                'ordering': ['-current_value'],
            },
        ),
        migrations.CreateModel(
            name='ValuationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_date', models.DateField(default=django.utils.timezone.now)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='估值(元)')),
                ('change_percent', models.FloatField(verbose_name='变化率(%)')),
                ('reason', models.CharField(max_length=200, verbose_name='估值原因')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='collection.wine')),
            ],
            options={
                'verbose_name': '估值历史',
                'verbose_name_plural': '估值历史',
                'ordering': ['-valuation_date'],
            },
        ),
    ]
