# Generated by Django 4.2.15 on 2026-06-09 13:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='申请人姓名')),
                ('applicant_id', models.CharField(max_length=50, verbose_name='身份证号')),
                ('applicant_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='电子邮箱')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='申请贷款金额(元)')),
                ('loan_term_months', models.IntegerField(verbose_name='贷款期限(月)')),
                ('interest_rate', models.FloatField(verbose_name='年利率(%)')),
                ('purpose', models.TextField(verbose_name='贷款用途')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('reviewing', '审核中'), ('approved', '已批准'), ('rejected', '已拒绝'), ('active', '还款中'), ('completed', '已结清'), ('defaulted', '已违约'), ('liquidated', '已处置')], default='draft', max_length=20, verbose_name='状态')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='申请日期')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='审核日期')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='批准日期')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='放款日期')),
                ('maturity_date', models.DateTimeField(blank=True, null=True, verbose_name='到期日期')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='批准金额(元)')),
                ('review_notes', models.TextField(blank=True, verbose_name='审核意见')),
                ('collateral_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='抵押品估值(元)')),
                ('ltv_ratio', models.FloatField(blank=True, null=True, verbose_name='抵押率(%)')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已还金额(元)')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='剩余金额(元)')),
            ],
            options={
                'verbose_name': '抵押申请',
                'verbose_name_plural': '抵押申请',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.IntegerField(verbose_name='期数')),
                ('due_date', models.DateField(verbose_name='还款日')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='应还本金(元)')),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='应还利息(元)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='应还总额(元)')),
                ('paid', models.BooleanField(default=False, verbose_name='是否已还')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='实际还款日期')),
                ('late_days', models.IntegerField(default=0, verbose_name='逾期天数')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='罚息(元)')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='mortgage.mortgageapplication')),
            ],
            options={
                'verbose_name': '还款计划',
                'verbose_name_plural': '还款计划',
                'ordering': ['payment_number'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='还款金额(元)')),
                ('payment_method', models.CharField(choices=[('bank_transfer', '银行转账'), ('alipay', '支付宝'), ('wechat', '微信支付'), ('cash', '现金'), ('other', '其他')], max_length=20, verbose_name='还款方式')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='交易流水号')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='还款日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='mortgage.repaymentschedule')),
            ],
            options={
                'verbose_name': '还款记录',
                'verbose_name_plural': '还款记录',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='MortgageCollateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='抵押数量(瓶)')),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价估值(元)')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总估值(元)')),
                ('storage_location', models.CharField(max_length=100, verbose_name='存放位置')),
                ('insurance_policy', models.CharField(blank=True, max_length=100, verbose_name='保单号')),
                ('appraisal_report', models.TextField(blank=True, verbose_name='评估报告')),
                ('released', models.BooleanField(default=False, verbose_name='是否已解押')),
                ('released_date', models.DateTimeField(blank=True, null=True, verbose_name='解押日期')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='mortgage.mortgageapplication')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mortgages', to='collection.wine')),
            ],
            options={
                'verbose_name': '抵押品',
                'verbose_name_plural': '抵押品',
            },
        ),
    ]
