# Generated by Django 4.2.15 on 2026-06-10 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TastingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='品鉴会名称')),
                ('theme', models.CharField(max_length=200, verbose_name='主题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('event_date', models.DateTimeField(verbose_name='活动时间')),
                ('location', models.CharField(max_length=200, verbose_name='地点')),
                ('organizer', models.CharField(max_length=100, verbose_name='主办方')),
                ('max_attendees', models.IntegerField(default=20, verbose_name='最大人数')),
                ('status', models.CharField(choices=[('upcoming', '待开始'), ('ongoing', '进行中'), ('completed', '已结束'), ('cancelled', '已取消')], default='upcoming', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tastings', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('wines', models.ManyToManyField(blank=True, related_name='tasting_events', to='collection.wine', verbose_name='品鉴酒品')),
            ],
            options={
                'verbose_name': '品鉴会',
                'verbose_name_plural': '品鉴会',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='TastingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='公司')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='职位')),
                ('checked_in', models.BooleanField(default=False, verbose_name='已签到')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='tasting.tastingevent', verbose_name='品鉴会')),
            ],
            options={
                'verbose_name': '签到人员',
                'verbose_name_plural': '签到人员',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='TastingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_rating', models.IntegerField(help_text='1-5分', verbose_name='颜色评分')),
                ('aroma_rating', models.IntegerField(help_text='1-5分', verbose_name='香气评分')),
                ('taste_rating', models.IntegerField(help_text='1-5分', verbose_name='口感评分')),
                ('finish_rating', models.IntegerField(help_text='1-5分', verbose_name='余味评分')),
                ('overall_rating', models.FloatField(editable=False, verbose_name='综合评分')),
                ('color_notes', models.TextField(blank=True, verbose_name='颜色描述')),
                ('aroma_notes', models.TextField(blank=True, verbose_name='香气描述')),
                ('taste_notes', models.TextField(blank=True, verbose_name='口感描述')),
                ('finish_notes', models.TextField(blank=True, verbose_name='余味描述')),
                ('general_notes', models.TextField(blank=True, verbose_name='综合评价')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasting_notes', to='tasting.tastingattendee', verbose_name='品鉴人')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasting_notes', to='tasting.tastingevent', verbose_name='品鉴会')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasting_records', to='collection.wine', verbose_name='酒品')),
            ],
            options={
                'verbose_name': '品鉴笔记',
                'verbose_name_plural': '品鉴笔记',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'wine', 'attendee')},
            },
        ),
    ]
