# Generated by Django 4.2.15 on 2026-06-09 13:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WineCellar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='酒窖名称')),
                ('location', models.CharField(max_length=200, verbose_name='位置')),
                ('capacity', models.IntegerField(verbose_name='容量(瓶)')),
                ('optimal_temp_min', models.FloatField(default=10.0, verbose_name='最佳温度下限(°C)')),
                ('optimal_temp_max', models.FloatField(default=15.0, verbose_name='最佳温度上限(°C)')),
                ('optimal_humidity_min', models.FloatField(default=60.0, verbose_name='最佳湿度下限(%)')),
                ('optimal_humidity_max', models.FloatField(default=80.0, verbose_name='最佳湿度上限(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '酒窖',
                'verbose_name_plural': '酒窖',
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='温度(°C)')),
                ('humidity', models.FloatField(verbose_name='湿度(%)')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cellar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.winecellar')),
            ],
            options={
                'verbose_name': '传感器读数',
                'verbose_name_plural': '传感器读数',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('temp_high', '温度过高'), ('temp_low', '温度过低'), ('humidity_high', '湿度过高'), ('humidity_low', '湿度过低')], max_length=20)),
                ('severity', models.CharField(choices=[('warning', '警告'), ('critical', '严重')], max_length=10)),
                ('status', models.CharField(choices=[('active', '未处理'), ('acknowledged', '已确认'), ('resolved', '已解决')], default='active', max_length=15)),
                ('value', models.FloatField(verbose_name='当前值')),
                ('message', models.TextField(verbose_name='告警消息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('cellar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.winecellar')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.sensorreading')),
            ],
            options={
                'verbose_name': '告警',
                'verbose_name_plural': '告警',
                'ordering': ['-created_at'],
            },
        ),
    ]
