# Generated by Django 4.2.15 on 2026-06-10 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='客户姓名')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, verbose_name='性别')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='电子邮箱')),
                ('id_card', models.CharField(blank=True, max_length=50, verbose_name='身份证号')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='联系地址')),
                ('level', models.CharField(choices=[('normal', '普通客户'), ('silver', '银卡会员'), ('gold', '金卡会员'), ('platinum', '白金会员'), ('diamond', '钻石会员')], default='normal', max_length=20, verbose_name='会员等级')),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='累计消费金额(元)')),
                ('total_orders', models.IntegerField(default=0, verbose_name='订单总数')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户档案',
                'verbose_name_plural': '客户档案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消'), ('returned', '已退货')], default='draft', max_length=20, verbose_name='订单状态')),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', '银行转账'), ('alipay', '支付宝'), ('wechat', '微信支付'), ('cash', '现金'), ('credit_card', '信用卡'), ('other', '其他')], max_length=20, verbose_name='支付方式')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='商品小计(元)')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='折扣金额(元)')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='运费(元)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='订单总额(元)')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下单时间')),
                ('confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('shipped_date', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('shipping_address', models.CharField(blank=True, max_length=300, verbose_name='收货地址')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='物流单号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '售出订单',
                'verbose_name_plural': '售出订单',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量(瓶)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价(元)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='总价(元)')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saleorder', verbose_name='订单')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='collection.wine', verbose_name='酒品')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
            },
        ),
        migrations.CreateModel(
            name='AuctionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='拍卖标题')),
                ('quantity', models.IntegerField(verbose_name='拍卖数量(瓶)')),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='起拍价(元)')),
                ('reserve_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='保留价(元)')),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='当前出价(元)')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='成交价(元)')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('upcoming', '即将开拍'), ('ongoing', '拍卖中'), ('ended', '已结束'), ('cancelled', '已取消')], default='upcoming', max_length=20, verbose_name='状态')),
                ('bid_count', models.IntegerField(default=0, verbose_name='出价次数')),
                ('auction_house', models.CharField(blank=True, max_length=200, verbose_name='拍卖行')),
                ('lot_number', models.CharField(blank=True, max_length=50, verbose_name='拍品编号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auctions', to='collection.wine', verbose_name='酒品')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions_won', to='sales.customer', verbose_name='中标客户')),
            ],
            options={
                'verbose_name': '拍卖记录',
                'verbose_name_plural': '拍卖记录',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='出价金额(元)')),
                ('bid_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='出价时间')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='sales.auctionrecord', verbose_name='拍卖')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='sales.customer', verbose_name='出价人')),
            ],
            options={
                'verbose_name': '拍卖出价',
                'verbose_name_plural': '拍卖出价',
                'ordering': ['-bid_time'],
            },
        ),
    ]
